apiVersion: v1
data:
  settings.py: |
    class BaseConfig(object):
        APP_SECRET = '0UC8fpFH9sUGww7_b8AjNmmLwEPl6u7b-NyWoezr1gUQfwH3bslOXp5C4znxC4c_'
        TOKEN = '870e202211382325783bcdf17b37a9f5a39e49fea1c94c44819e18ee8e59cbe1'
        ENVPARA= ('fz' ,'cs', 'lt', 'dj')
        TESTTYPE = ('bvt', 'all')
kind: ConfigMap
metadata:
  name: checkservice-settings
