apiVersion: v1
data:
  settings.py: |+
    class BaseConfig(object):
        URL = 'http://spboot.bigtreefinance.com/admin/applications'
        RISK_URL = 'https://risk.bigtreefinance.com/api/management/error'
        APP_SECRET = '0UC8fpFH9sUGww7_b8AjNmmLwEPl6u7b-NyWoezr1gUQfwH3bslOXp5C4znxC4c_'
        NACOS = 'https://nacos.k7.bigtree.tech/nacos/v1/ns/catalog/services?hasIpCount=true&withInstances=false&pageNo=1&pageSize=100&serviceNameParam=&groupNameParam=&accessToken={}&namespaceId=btfdp'
        RX_NACOS = 'http://nacos.btrx.k7.bigtree.tech/nacos/v1/ns/catalog/services?hasIpCount=true&withInstances=false&pageNo=1&pageSize=100&serviceNameParam=&groupNameParam=&accessToken={}&namespaceId=btrx'
        IFBC_NACOS = 'http://nacos.btifbc.k7.bigtree.tech/nacos/v1/ns/catalog/services?hasIpCount=true&withInstances=false&pageNo=1&pageSize=100&serviceNameParam=&groupNameParam=&accessToken={}&namespaceId=btifbc'
        SCV_LIST = ("bigtree-audit",
                    "bigtree-auth",
                    "bigtree-credit",
                    "bigtree-event",
                    "bigtree-file",
                    "bigtree-front",
                    "bigtree-gateway",
                    "bigtree-invoice",
                    "bigtree-message",
                    "bigtree-mq",
                    "bigtree-pay",
                    "bigtree-questionnaire",
                    "bigtree-scfp",
                    "bigtree-sign",
                    "bigtree-system",
                    "bigtree-workflow",
                    "qsls-app",
                    "qsls-back",
                    "qsls-batch",
                    "qsls-channel",
                    "qsls-client",
                    "qsls-cst",
                    "qsls-expense",
                    "qsls-finance",
                    "qsls-front",
                    "qsls-fund",
                    "qsls-limit",
                    "qsls-newexpense",
                    "qsls-postloan",
                    "qsls-receivable",
                    "qsls-referee",
                    "qsls-thirdparty"
                    )
        NACOS_LIST = ("fund-platform",
                      "fund-batch",
                      "fund-bank-sx",
                      "datawarehouse-platform",
                      "fund-bank-shanmei",
                      "bigtree-file",
                      "fund-gateway",
                      "bigtree-system",
                      "bigtree-message-nacos",
                      "fund-bank-wh",
                      "fund-bank-qs",
                      "fund-bank-xiaowei",
                      "fund-payment-unionpay",
                      "fund-bank-zx"
                    )
        RX_NACOS_LIST = ("rx-batch",
                         "rx-job-admin",
                         "rx-gateway",
                         "rx-sign",
                         "rx-customer",
                         "rx-app",
                         "rx-back",
                         "rx-system",
                         "rx-auth",
                         "rx-message",
                         "rx-file",
                         "rx-pay"
                    )
        IFBC_NACOS_LIST = ("ifbc-admin-platform",
                          "ifbc-app",
                          "ifbc-auth",
                          "ifbc-batch",
                          "ifbc-business",
                          "ifbc-channel",
                          "ifbc-credit",
                          "ifbc-customer",
                          "ifbc-diamond",
                          "ifbc-file",
                          "ifbc-flow",
                          "ifbc-fund-trade",
                          "ifbc-fund",
                          "ifbc-gateway",
                          "ifbc-identify",
                          "ifbc-job-admin",
                          "ifbc-message",
                          "ifbc-product",
                          "ifbc-sign",
                          "ifbc-system"
                    )
        NICK_LIST = ("苏合信", "常蒙蒙")

    class APSchedulerJobConfig(BaseConfig):
        SCHEDULER_API_ENABLED = True
        SCHEDULER_TIMEZONE = 'Asia/Shanghai'
        MYTOKEN = 'f8e5c0d09f615101e6067428996af309ec3cbdbd20d31a8cb241b4fb8995f4a2'
        TOKEN = 'ce233ed37d66c1f38dfef475790708e387ef4451e85da50d20af994e81d52409'
        RXTOKEN = 'b287bdf8ecca0b708ad1c4de8c7bdeb7bf63780243976f8c70900eac77296ed2'

        JOBS = [
            {
                'id': 'No1',
                'func': 'app:check_service',
                'args': '',
                'trigger': {
                    'type': 'cron',
                    'day_of_week': 'mon-sun',
                    'hour': '13, 22',
                    'minute': '15'
                }
            }
        ]

kind: ConfigMap
metadata:
  name: checkservice-settings
  namespace: ops
