apiVersion: v1
data:
  settings.py: |+
    class BaseConfig(object):
        URL = 'http://spboot.bigtreefinance.com:8080/admin/applications'
        APP_SECRET = '3yCIyIjvAnvpokzZrrS2RC4M6TGVU4IsliouUot8PIktvRVPTrSSrueyzdb2vSTe'
        SCV_LIST = ("bigtree-auth",
                    "bigtree-sign",
                    "bigtree-mq",
                    "qsls-limit",
                    "bigtree-invoice",
                    "bigtree-gateway",
                    "qsls-expense",
                    "bigtree-credit",
                    "bigtree-system",
                    "bigtree-message",
                    "qsls-batch",
                    "qsls-cst",
                    "bigtree-front",
                    "qsls-back",
                    "bigtree-scfp",
                    "bigtree-workflow",
                    "bigtree-event",
                    "qsls-client",
                    "qsls-finance",
                    "qsls-front",
                    "bigtree-file",
                    "qsls-postloan",
                    "qsls-receivable",
                    "qsls-app",
                    "bigtree-pay"
                    )

    class APSchedulerJobConfig(BaseConfig):
        SCHEDULER_API_ENABLED = True
        SCHEDULER_TIMEZONE = 'Asia/Shanghai'
        JOBS = [
            {
                'id': 'No1',
                'func': 'app:check_service',
                'args': '',
                'trigger': {
                    'type': 'cron',
                    'day_of_week': 'mon-sun',
                    'hour': '13, 22',
                    'minute': '10'
                }
            }
        ]

kind: ConfigMap
metadata:
  name: checkservice-settings
  namespace: ops
