apiVersion: v1
kind: Service
metadata:
  name: checkservice
  namespace: ops
spec:
  type: ClusterIP
  selector:
    app: checkservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
